### ISSUE TITLE
doesn't work with NextJs

### ISSUE THREAD

**Issue by sgehrman** [imbhargav5/rooks#1234]
ReferenceError: window is not defined
    at useOnWindowScroll (/home/steve/Documents/GitHub/mavrik/fe-infinity/node_modules/rooks/dist/cjs/hooks/useOnWindowScroll.js:19:70)
    at useWindowScrollPosition (/home/steve/Documents/GitHub/mavrik/fe-infinity/node_modules/rooks/dist/cjs/hooks/useWindowScrollPosition.js:34:47)
    at HomePage (webpack-internal:///./pages/index.tsx:48:89)
    at processChild (/home/steve/Documents/GitHub/mavrik/fe-infinity/node_modules/react-dom/cjs/react-dom-server.node.development.js:3353:14)
    at resolve (/home/steve/Documents/GitHub/mavrik/fe-infinity/node_modules/react-dom/cjs/react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (/home/steve/Documents/GitHub/mavrik/fe-infinity/node_modules/react-dom/cjs/react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (/home/steve/Documents/GitHub/mavrik/fe-infinity/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
    at Object.renderToString (/home/steve/Documents/GitHub/mavrik/fe-infinity/node_modules/react-dom/cjs/react-dom-server.node.development.js:4298:27)
    at Object.renderPage (/home/steve/Documents/GitHub/mavrik/fe-infinity/node_modules/next/dist/server/render.js:662:46)
    at Object.defaultGetInitialProps (/home/steve/Documents/GitHub/mavrik/fe-infinity/node_modules/next/dist/server/render.js:286:51)

**Comment by imbhargav5** [comment]
@gmahima This one was the issue we talked about. Give it a shot!

**Comment by imbhargav5** [comment]
@sgehrman Could you check 6.4.2? It is working for me. Thanks!
